### ISSUE TITLE
Hangs in conjunction with other postcss modules

### ISSUE THREAD

**Issue by anandthakker** [anandthakker/doiuse#10]
See anandthakker/doiuse.com#26

**Comment by anandthakker** [comment]
I believe this is fixed in 0.3.3, but leaving this issue open till a test is added for it.

**Comment by onemanstartup** [comment]
I'm having this error with doiuse@1.0.3
```
ERROR in ./~/css-loader!./~/postcss-loader!../base/~/normalize.css/normalize.css
Module build failed: TypeError: css.prevMap.consumer is not a function
  at /Users/onemanstartup/Code/awesome/insaneapp/node_modules/doiuse/lib/doiuse.js:38:30
```

**Comment by anandthakker** [comment]
Ah, okay.  Thanks @onemanstartup -- any chance you could include the postcss code that's running this?

**Comment by anandthakker** [comment]
Just updated the postcss api - can you check if [1.0.4](https://github.com/anandthakker/doiuse/commit/75c2d5f8e663ba68f2c1ceffdadc67a493c7050b) fixes this for you, @onemanstartup ?

**Comment by onemanstartup** [comment]
@anandthakker yeah, this fixed the error. Thanks.
And sorry for not responding, I lost in time.

**Comment by anandthakker** [comment]
:+1:
