### ISSUE TITLE
specify files?

### ISSUE THREAD

**Issue by badtant** [anandthakker/doiuse#103]
Hi,

I'm trying to use the JS example don't understand how to specify which files to check.
These is a ignoreFiles option but no files option?

Thanks

**Comment by brettz9** [comment]
The JS API is apparently meant to be used with `postcss`.

The `doiuse` function does not accept files but instead returns an object with a `postcss` callback, and it is that callback which gets passed the files (based on the`css` object passed into it): https://github.com/anandthakker/doiuse/blob/master/src/doiuse.js#L37 . You'd have to look at [`postcss`](http://api.postcss.org/postcss.html) to understand how this is processed.
