### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by marekdedic** [anandthakker/doiuse#110]
There have been no commits in quite some time and the issues and PRs keep piling... So, is this project abandoned?

**Comment by ismay** [comment]
I wouldn't call it abandoned. But it doesn't seem to be actively maintained. The owner is very open to outside help though, so I'm sure that if someone would step up and take care of the outstanding issues/PRs he'd be very supportive. It's just that no one has so far.

**Comment by anandthakker** [comment]
^ that's accurate.  I'd also be open to transferring ownership to, e.g., the postcss organization, if the maintainers there were interested

**Comment by marekdedic** [comment]
@ai ? :)

**Comment by ai** [comment]
I can promote that you are looking maintainer in PostCSS twitter.

Also you should look at who do use your tool as dependency. The best way is to give them an access.

**Comment by timbru31** [comment]
Any updates on this? Last release and commit in 2018, some open issues and PRs and a npm audit warnings. :(

**Comment by JackHowa** [comment]
@timbru31 yeah I saw the warning elsewhere as well with yargs: 

https://github.com/anandthakker/doiuse/pull/120

**Comment by pkuczynski** [comment]
@anandthakker can you transfer ownership to me? I still don't have full rights on the github project :(
