### ISSUE TITLE
Not getting warnings for logical border-radius properties

### ISSUE THREAD

**Issue by t0byman** [anandthakker/doiuse#139]
These 4 logical properties won't trigger a no supported warning for Safari, how come?

- border-start-start-radius
- border-start-end-radius
- border-end-start-radius
- border-end-end-radius

My browserslist is:
`"> 1%",
"last 1 Android versions",
"last 1 ChromeAndroid versions",
"last 2 Chrome versions",
"last 2 Firefox versions",
"last 2 Safari major versions",
"last 2 iOS major versions",
"last 2 Edge versions",
"last 2 Opera versions",
"not op_mini all"`

Caniuse says the properties above aren't supported by Safari so shouldn't I get the warnings?

**Comment by clshortfuse** [comment]
Fixed:

````
echo "body {border-start-start-radius: 5px}"| npx d
oiuse --browsers "ie >= 9"
<streaming css input>:1:1: CSS Logical Properties not supported by: IE (9,10,11) (css-logical-props)
````
