### ISSUE TITLE
Not getting warnings for logical position properties (inset)

### ISSUE THREAD

**Issue by t0byman** [anandthakker/doiuse#140]
These 7 logical properties won't trigger a no supported warning for Safari, how come?

- inset
- inset-block
- inset-block-start
- inset-block-end
- inset-inline
- inset-inline-start
- inset-inline-end

My browserslist is:
`"> 1%",
"last 1 Android versions",
"last 1 ChromeAndroid versions",
"last 2 Chrome versions",
"last 2 Firefox versions",
"last 2 Safari major versions",
"last 2 iOS major versions",
"last 2 Edge versions",
"last 2 Opera versions",
"not op_mini all"`

As of writing that would mean Safari 13 and 14. Caniuse says the properties above aren't supported by Safari 13 (support for inset starts at 14.1) so shouldn't I get the warnings?

**Comment by clshortfuse** [comment]
Fixed:

````
echo "body{inset-inline-end:0}"| npx doiuse --browsers "kaios >= 2.5"
<streaming css input>:1:1: CSS Logical Properties only partially supported by: KaiOS Browser (2.5) (css-logical-props)
````
