### ISSUE TITLE
Remove dependency range from `caniuse-lite`

### ISSUE THREAD

**Issue by Jameskmonger** [anandthakker/doiuse#193]
`caniuse-lite` and `caniuse-db` do not respect semantic versioning.

Recently, a breaking change was published under a patch update (`1.0.30001654` -> `1.0.30001655`)  (you can read more in these two issues: https://github.com/browserslist/caniuse-lite/issues/129, https://github.com/RJWadley/stylelint-no-unsupported-browser-features/issues/299)

It is therefore dangerous to accept a semantic version range in for `caniuse-lite`, `doiuse` has caused breaking changes to bleed into dependant projects due to this

**Comment by Jameskmonger** [comment]
> install this
> 
> **dangerous link removed** If you don't have the c compliator, install it.(gcc or clang)

Needless to say, do not click the link in the comment above

**Comment by clshortfuse** [comment]
Fixed in af3845d166474665b5e316cdb82d622dee504a97

**Comment by Jameskmonger** [comment]
Thanks for the prompt resolution @clshortfuse!
