### ISSUE TITLE
fix: cannot read properties of undefined (reading 'some') in v6.0.3

### ISSUE THREAD

**Issue by dargmuesli** [anandthakker/doiuse#195]
Hmm, I think something broke with v6.0.3:

![image](https://github.com/user-attachments/assets/b5f6c4c8-3ee9-475c-9e91-b2495e770bea)

Seems like this `.some` here works differently now: https://github.com/anandthakker/doiuse/commit/5199d866ed88d86b2c833078ee62264bb9604226

**Comment by clshortfuse** [comment]
Do you have a reproducible? The last commit on that file is https://github.com/anandthakker/doiuse/blob/14b4c0d128b1fb1f45619aa5db87417b8b2292b4/data/features/flexbox-gap.js
and it has a check for .some

`if (!('some' in rule)) return false;`

**Comment by dargmuesli** [comment]
Correct, `this.nodes` is empty (while `some` is fine). I haven't created a reproducible myself yet, but the screenshot comes from this renovate PR which updated doiuse to v6.0.3: https://github.com/dargmuesli/vio/actions/runs/11005452662/job/30558159103?pr=233#step:7:826
I'll come back to this when time allows :runner:

**Comment by dargmuesli** [comment]
Added a fix in #196 :raised_hands:

**Comment by MuTsunTsai** [comment]
Having the same issue with the same cause. Looking forward for the fix.

**Comment by dargmuesli** [comment]
Fyi @clshortfuse it seems the last release was not tagged on GitHub and therefore there is also no release visible. Maybe that's on your radar already, I just want to mention it in case it isn't.
