### ISSUE TITLE
onFeatureUsage callback vs. PostCSS result.warn

### ISSUE THREAD

**Issue by sebastienbarre** [anandthakker/doiuse#24]
I was wondering about the rational behind using the `onFeatureUsage` [callback](https://github.com/anandthakker/doiuse/blob/master/src/doiuse.js#L39) in the PostCSS plugin? Wouldn't PostCSS's [`result.warn()`](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#32-use-resultwarn-for-warnings) API make more sense? In that way warnings would flow through PostCSS, and could potentially be pretty-printed by [`postcss-reporter`](https://github.com/postcss/postcss-reporter).
Alternatively, maybe both could be used?
Thank you.
(I can work on a PR if needed)

**Comment by sebastienbarre** [comment]
With respect to the PostCSS plugin, what about this: if the `onFeatureUsage` callback is *not* set, then we use PostCSS's `result.warn` to send the warning message (which in turn can be intercepted and pretty-printed by `postcss-reporter`). This doesn't break any API, and people can still silence `doiuse` by providing an empty callback (then again, I'm not sure why you wouldn't want to see the warnings). I can push a PR along these lines.

**Comment by anandthakker** [comment]
Closed by #26
