### ISSUE TITLE
Ignore a file based on name

### ISSUE THREAD

**Issue by SevereOverfl0w** [anandthakker/doiuse#29]
Would it be possible to ask doiuse to ignore a file based on name? I have Normalize.css being imported via postcss-import, and as it has a lot of browser-specific fixes in there, it's upsetting doiuse.

I have seen that you've slowed down on development, and would be happy to open a PR if you think it's relatively feasible within the codebase.

**Comment by anandthakker** [comment]
@SevereOverfl0w Hmm -- well, I'm certainly open to it, although if imports are happening before doiuse gets to the CSS, it might be hard to know exactly what came from each file.

**Comment by SevereOverfl0w** [comment]
Doiuse is picking up the filename, I'm not entirely sure how though! But
its definitely correct.

I'll have a go soon!

**Comment by SevereOverfl0w** [comment]
doiuse is picking up the filename, as a node's source has a "file" attribute, which is the original file the line comes from.

**Comment by anandthakker** [comment]
Ah, right.  Happy to take a PR on it--otherwise, I'd definitely like to add
it, but it might take a little while before I'll have time..

**Comment by SevereOverfl0w** [comment]
Yep, it should be a fairly simple addition. I'll pull in minimatch, and match it against the path. I'll find some time in the next couple days to add it.

**Comment by anandthakker** [comment]
:+1:

**Comment by anandthakker** [comment]
Closed by #30
