### ISSUE TITLE
support to load config browserlist

### ISSUE THREAD

**Issue by evilebottnawi** [anandthakker/doiuse#37]
https://github.com/ai/browserslist#config-file

**Comment by Gurylev** [comment]
+1

**Comment by StefanSchwartze** [comment]
+1

Something like this would be great:

`var custom = {
    ie: {
        6: 0.01,
        7: 0.4,
        8: 1.5
    },
    chrome: {
        …
    },
    …
};`

**Comment by cronfy** [comment]
Would be useful for me too. Like here: https://github.com/postcss/postcss-loader#autoprefixer set up browserslist for all plugins at once.

**Comment by stevewillard** [comment]
Definitely would like this feature. +1

**Comment by stevewillard** [comment]
Do you mind cutting a release for this feature?

**Comment by niftylettuce** [comment]
Is there still not a release for this?  It doesn't seem to work yet.

**Comment by niftylettuce** [comment]
Yeah this isn't in 4.0.0 at all, this basically doesn't work out of the box unless you specify a `browsers` option that's hardcoded string.  Defeats purpose of browserslist standard.
