### ISSUE TITLE
Messages whitespace in 2.4.0

### ISSUE THREAD

**Issue by ntwb** [anandthakker/doiuse#48]
Over in @stylelint/stylelint updating to doiuse 2.4.0 one of our tests returns:

`... is not fully supported by IE 9 and  only partially supported...`

There are actually two spaces between `and` and `only` above.

• `and ` includes a space after it here: [/doiuse/blob/master/src/doiuse.js#L44](https://github.com/anandthakker/doiuse/blob/master/src/doiuse.js#L44)
• ` only` includes a space before it here: [/doiuse/blob/master/src/doiuse.js#L41](https://github.com/anandthakker/doiuse/blob/master/src/doiuse.js#L41)

It would be great if one of these spaces were removed :)

**Comment by anandthakker** [comment]
@ntwb ah, yep - thanks for catching that.

**Comment by anandthakker** [comment]
Fixed in 2.4.1

**Comment by ntwb** [comment]
Awesome, thanks @anandthakker 👍
