### ISSUE TITLE
Expose more metadata

### ISSUE THREAD

**Issue by jeddy3** [anandthakker/doiuse#49]
Firstly, thanks for such a useful tool!

We wrap it in stylelint as the [`no-unsupported-browser-features`](https://github.com/stylelint/stylelint/tree/master/src/rules/no-unsupported-browser-features) rule. 

At the moment we [pull doiuse's messages apart](https://github.com/stylelint/stylelint/blob/master/src/rules/no-unsupported-browser-features/index.js#L53-L65) so we can make them consistent with [stylelint's conventions](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#determine-warning-messages), but this approach [is quite fragile](https://github.com/stylelint/stylelint/pull/1638).

Would it be possible to expose the browser support results within the doiuse warning? stylehacks (which we wrap as the [`no-browser-hacks`](https://github.com/stylelint/stylelint/tree/master/src/rules/no-browser-hacks) rule) did it [like so](https://github.com/ben-eb/stylehacks/pull/6), and we simply consume this extra metadata [like so](https://github.com/stylelint/stylelint/blob/master/src/rules/no-browser-hacks/index.js#L35).

I think something along the lines of the following would be ideal:

``` js
result.warn(message, { 
  node: usage, 
  plugin: 'doiuse'
  support: {
    full: [{
      browser: "IE",
      versions: [7, 8, 9]
    }, {
      browser: "Chrome",
      version: [23, 34]
    }],
    partial: [{
      browser: "Opera Mini",
      versions: [1, 2, 3]
    }], 
})
```

Do you think such a thing would be possible?

**Comment by StefanSchwartze** [comment]
Sounds very useful to me, I also would need more data like that. The question is, how will the output data then look like… Will we include the full name? Or a slug? I think this needs some discuss.

**Comment by jeddy3** [comment]
> Sounds very useful to me

Good stuff!

> Will we include the full name? Or a slug?

I guess the more metadata the better. Can we include both?:

```js
{
  fullName: "Opera Mini",
  slug: "mini",
  versions: [1, 2, 3]
}
```

**Comment by StefanSchwartze** [comment]
Of course we can. But I think it would be more consistent to reuse the data provided by the module. Like the following format (described in missing-support.js):

```js
missingData: {
// map of browser -> version -> (lack of)support code
 ie: { '8': 'n' },
 chrome: { '31': 'n' }
}
partialData: {
// map of browser -> version -> (partial)support code
 ie: { '7': 'a' },
 ff: { '29': 'a #1' }
}
```

With this, it is still possible to find out for example why something is only partially reported, because the support refers to the information provided by "featureData". What do you (and maybe also @anandthakker)  think about that?

**Comment by anandthakker** [comment]
I'm not up to speed on the postcss API, but if `result.warn` can accept arbitrary metadata I'm all for it.

How about just including something like: https://github.com/anandthakker/doiuse/blob/master/src/doiuse.js#L62-L63

**Comment by jeddy3** [comment]
> How about just including something like:

I'm not too familiar with the internals of doiuse. Could you knockup a quick example of what some data would look like if those two properties were used?

**Comment by anandthakker** [comment]
@jeddy3 Sure thing, here's an example of the the full object that's output in the lines linked above: https://gist.github.com/anandthakker/83002ac1e12d201fa8c2906990d4978c 

You can also see others if you use the `-j` option with the cli, e.g. `doiuse -j my-css.css`

**Comment by jeddy3** [comment]
Thanks for sharing that. 

Am I right in thinking that'd we'd need to something similar to contents of  [`missing-support.js`](https://github.com/anandthakker/doiuse/blob/master/src/missing-support.js) and [`util.js`](https://github.com/anandthakker/doiuse/blob/master/src/util.js) *within the stylelint plugin* to humanise the data?

If so, as you're already humanising the data for when this tool is used unwrapped, would it be wise to include this humanised data alongside the source from which it's built? e.g.

```js
{
  support: 
    featureData: { ... }
    humanized: {
      full: [{
        browser: "IE",
        versions: [7, 8, 9]
      }, {
        browser: "Chrome",
        version: [23, 34]
      }],
      partial: [{
        browser: "Opera Mini",
        versions: [1, 2, 3]
      }],
    }
  }
}
```

That seems to expose both the raw results and the humanised data. Two useful things this tool does and would be beneficial to other modules.

**Comment by anandthakker** [comment]
Hmm, I see what you're saying, but I'm feeling somewhat hesitant to include an additional output here that can be derived without too much extra work from the existing output.  Did you see [this part](https://gist.github.com/anandthakker/83002ac1e12d201fa8c2906990d4978c#file-output-json-L246-L273) of the output?

```json
 "missingData": {
      "opera": {
        "12.1": "n"
      },
      "op_mini": {
        "5.0-8.0": "n"
      }
    },
    "partialData": {
      "safari": {
        "8": "a",
        "9": "a"
      },
      "ios_saf": {
        "8.1-8.4": "a",
        "9.0-9.1": "a"
      },
      "android": {
        "4.2-4.3": "a",
        "4.4": "a",
        "4.4.3-4.4.4": "a"
      },
      "and_uc": {
        "9.9": "a"
      }
    }
```

It seems to me that the main thing you'd need within stylelint to "humanizing" either `partialData` or `missingData` is the `formatBrowserName` function, which you could simply require with something like `var formatBrowserName = require('doiuse/lib/util').formatBrowserName`.

@jeddy3 ^ does an approach like this sound viable for you?

**Comment by StefanSchwartze** [comment]
This is exactly what I meant 5 posts earlier, with featureData + missing/partialData it is possible to get every humanized data, without having to Regex strings or something similiar.

**Comment by jeddy3** [comment]
> @jeddy3 ^ does an approach like this sound viable for you?

Yes, that sounds great. 

Thanks for your patience helping me wrap my head around it :)

**Comment by clshortfuse** [comment]
Closing since issue seems outdated.
