### ISSUE TITLE
on issues the doiuse CLI should exit the process with an exit code > 0

### ISSUE THREAD

**Issue by varemenos** [anandthakker/doiuse#54]
Currently even if the cli finds an issue with your css file it doesn't exit properly making it impossible to track for issues via shell (this should also apply to the postcss processor). Basically the cli's process should exit with an exit code greater than 0 and the postcss processor should notify postcss of the issues so it can exit it's process.

**Comment by anandthakker** [comment]
Agreed that the CLI should exit nonzero when there's an issue.

**Comment by varemenos** [comment]
I wouldn't mind working on a PR if you'd be willing to assist me a bit.
It seems like there are certain restrictions making this kinda hard to implement (mostly finding the right location to `process.exit(1)`) since we have to make sure it doesn't stop executing once it finds an issue (to be able to print all issues and not just the latest one), plus this could lead to a braking change.

What I have in mind right now on implementing it is to create an Array (or a Number var) in which we'd keep the issues and once doiuse is done executing, we check whether the length (or value) of the arr/variable is greater than 0 and then exit with exit code > 0 instead of exiting with 0.
