### ISSUE TITLE
Required module not listed as dependency

### ISSUE THREAD

**Issue by paazmaya** [anandthakker/doiuse#6]
A package used in https://github.com/anandthakker/doiuse/blob/master/cli.js#L6
is not included in the `package.json` `dependencies` list, thus resulting error after installed globally:

```
$ doiuse --help

module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
```

Possible fix would be to listing it as a dependency...

**Comment by anandthakker** [comment]
Thanks for the report!

**Comment by anandthakker** [comment]
@paazmaya Should be fixed, but please let me know if not!
