### ISSUE TITLE
Do not look for browserslist manually

### ISSUE THREAD

**Issue by ai** [anandthakker/doiuse#67]
Hi. I am author of PostCSS and Browserslist. Thanks for you project, it is really important for PostCSS.

It is great that you use Browserslist — common configs make our ecosystem stronger.

But I found that you use Browserslist with wrong API. You pass only browsers query and didn’t pass `path` option with input file. As result Browserslist doesn’t look for it config. You try to solve it by looking for `browserslist` config manually. But you parse it in wrong way, forget about comments.

As result, I have issue reports like this: https://github.com/ai/browserslist/issues/135

But all this problems is very easy to solve — just pass `path` option to Browserslist and remove own code to find config. Less code is always better for maintenance. As result you will support many new features from Browserslist (config in `package.json` for instance).

@anandthakker say if you need PR for it

/cc @ch2ch3

**Comment by ai** [comment]
@anandthakker any updates? What do you think about this issue. Do you need something?

I really care about it, because it is critical for PostCSS ecosystem and could be fixed very easy.

**Comment by wrumsby** [comment]
@ai I'll try to look at it in the next week or so.

**Comment by ismay** [comment]
People using `stylelint-no-unsupported-browser-features` are running into this too. Apparently atom has trouble parsing the browsersupport because of this and, as @ai mentioned, comments in the config break doiuse as well.

**Comment by ismay** [comment]
@wrumsby Any news on this? I just had another issue about the non-standard parsing of the browserslist by doiuse.

**Comment by ai** [comment]
@wrumsby hi, it is still very critical for PostCSS ecosystem :)

**Comment by anandthakker** [comment]
Hey all -- apologies for the delay in responding here: I have been entirely away from GitHub for several weeks now, for family reasons.  

Totally on board with a PR to fix this -- I'm going to be *very* swamped getting caught up at my day job, though.  @ai I will add you as a member to this repo, though, in case you're able to help get a PR merged.

**Comment by ai** [comment]
@anandthakker thanks. I finished most of changes (I also updated PostCSS and moved from `caniuse-db` to `caniuse-lite` as we did in Autoprefixer and Browserslist). RIght now I am waiting for next `caniuse-lite` release (we added some missed data for your project) and I will send PR.

**Comment by ai** [comment]
@anandthakker done https://github.com/anandthakker/doiuse/pull/69
