### ISSUE TITLE
Remove some browsers

### ISSUE THREAD

**Issue by gvmohzibat** [anandthakker/doiuse#74]
How can I remove some browsers from the list of browsers being checked? For example for me Opera mini is not important so I don't want to get warnings for that.

**Comment by ismay** [comment]
Please check the [browserslist docs](https://github.com/ai/browserslist) for info on how to do that. Thanks!

**Comment by cebreus** [comment]
> How can I remove some browsers from the list of browsers being checked? For example for me Opera mini is not important so I don't want to get warnings for that.

```
not OperaMini all
```
