### ISSUE TITLE
No results for "caret-color" (in VScode)

### ISSUE THREAD

**Issue by ViggoV** [anandthakker/doiuse#76]
I have a hard time figuring out if this is working or not. I've been fiddling with the browser array for a while (after realising that i had to reload the window each time) and now have the following array:

`["ie >= 10", "> 1% in DK", "not OperaMini"]`

However, when I add `caret-color` to my stylesheet I get no results from Doiuse. According to caniuse.com there is no support for that in IE10 or 11..

Am I missing something? Are the caniuse API not entirely up to date? Something else?

**Comment by clshortfuse** [comment]
Fixed in #159 

````
echo 'body{caret-color:pink}' | npx doiuse --browsers "ie >= 8"
<streaming css input>:1:1: CSS caret-color not supported by: IE (8,9,10,11) (css-caret-color)
````
