### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by ismay** [anandthakker/doiuse#79]
@anandthakker @ai I regret to say that I wont be able to contribute to this repository anymore. Since accepting membership to this repository I've tried to combine maintenance on this repo with that on my other projects, but I haven't been able to find the time to do so.

So I've decided to just focus on a couple of my projects, and do that well, instead of half assing more projects. I'm sorry that I am not able to contribute any more, because I think this is an awesome project, so I hope you'll find some people soon!

**Comment by pkuczynski** [comment]
Maintainer found ;)

**Comment by ismay** [comment]
Great news 😊🎉🎉! Thanks for helping out!

**Comment by pkuczynski** [comment]
@ismay I have no access to Settings, so I can not add more maintainers. Can you help with that?
