### ISSUE TITLE
False positives when using css variables

### ISSUE THREAD

**Issue by ismay** [anandthakker/doiuse#82]
Variables that match css declarations are being incorrectly interpreted as those declarations and not as variables. See [here](https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/45#issuecomment-352242279) for further discussion on where exactly it's going wrong.

**Comment by clshortfuse** [comment]
Original issue sites:

```scss
.class {
  width:rem-calc(20px);
}
````

Passing scss directly into `doiuse` isn't really supported, nor should it be. `scss` is a preprocessor. Whatever `rem-calc` does in SCSS should transform into `css` before landing in `doiuse`.

Also, this isn't really CSS variables (which are different thing). This seems like custom CSS functions which aren't part of any spec. We can explore that later if that ever happens.
