### ISSUE TITLE
Publish browserslist update

### ISSUE THREAD

**Issue by ismay** [anandthakker/doiuse#86]
@pkuczynski I saw that browserslist has been updated, but it seems like it hasn’t been published. Was wondering if there’s an e.t.a. on that, because I’d like to use the new version with my stylelint plugin.

**Comment by pkuczynski** [comment]
I will publish new version on Monday. Ping me in case it won’t happen. Pretty busy last weeks

**Comment by ismay** [comment]
Sounds good, thanks!👌

**Comment by ismay** [comment]
@pkuczynski Just pinging as a reminder

**Comment by pkuczynski** [comment]
Done as v4.1.0
