### ISSUE TITLE
BrowserList object is ignored

### ISSUE THREAD

**Issue by ffoodd** [anandthakker/doiuse#89]
I'm currently trying to use DoIUse piped in a Gulp task, this way:
```javascript
gulp.task('compat', function() {
  fs.createReadStream(test.css)
    .pipe(doiuse(['Firefox ESR']))
    .on('data', function(usageInfo) {
       console.log(usageInfo.message)
     })
});
```

But whatever I give to the browserList object, it's ignored.

And that makes DoIUse very, very, very wordy. 

Am I missing something?

**Comment by budarin** [comment]
I have this bug too [#70](https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/70)

**Comment by pkuczynski** [comment]
@ffoodd you would have to run it like this:

```
doiuse({browsers: ['Firefox ESR']})
```
