### ISSUE TITLE
css-variables are ignored

### ISSUE THREAD

**Issue by ppseprus** [anandthakker/doiuse#90]
I believe, _css-variables_ are ignored by _doiuse_.

**Steps to reproduce**
1. Create the _test.css_ file with the following content
```
:root {
  --foo: red;
}
div {
  background-color: var(--foo);
}
```
2. Then, run the following command: `doiuse --browsers "ie 6" test.css`
(for details: https://caniuse.com/#feat=css-variables)

**Current behaviour**
The following error is returned: `test.css:1:1: CSS3 selectors not supported by: IE (6) (css-sel3)`
https://caniuse.com/#feat=css-sel3

**Expected behaviour**
An error for the following feature is also returned by _doiuse_:
https://caniuse.com/#feat=css-variables

**Note**
I've also tried the following code, where no error was returned.
```
div {
  --foo: red;
  background-color: var(--foo);
}
```

**Comment by clshortfuse** [comment]
Fixed in v5.0
