### ISSUE TITLE
Browserlist key in package.json ignored

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [anandthakker/doiuse#92]
I have my browsers set in the package.json so that multiple plugins can pull from the same list (autoprefixer included)

Can you please add compatibility for this to your plugin as when I leave the browsers option blank it fails, meaning I can't use a unified list.

Thanks,

**Comment by pkuczynski** [comment]
@mikeybinnswebdesign we are using the latest `browserslist` so the problem should not exist... Could you maybe create example repo to showcase the problem?

**Comment by mikeybinnswebdesign** [comment]
@pkuczynski sure, I will first make sure I update and check again as it has been a month since I posted the issue. I will check this now and let you know if im still having issues. Can you let me know what you need in the repo? Would it just be the gruntfile and the package.json?

**Comment by pkuczynski** [comment]
Yes, that would be enough. Your config and one css file in 'src' folder which you would be testing for. So basically an example repo...

**Comment by mikeybinnswebdesign** [comment]
I've updated and this is working now.

Thanks.
