### ISSUE TITLE
Poor performance of a particular example on ie 6

### ISSUE THREAD

**Issue by marekdedic** [anandthakker/doiuse#95]
Hi I get very poor performance for elements with `:focus:hover` when checking them against `ie 6`.
Example:
```zsh
$ time doiuse --browsers "ie 6" example.css
example.css:1:1: CSS 2.1 selectors not supported by: IE (6) (css-sel2)
doiuse --browsers "ie 6" example.css  59,04s user 0,06s system 100% cpu 59,014 total
```
where `example.css` is:
```css
.imagelightbox-arrow:focus:hover {
}
```

I've found that changing the name of the class sometimes resolves the issue, as does removing either the `hover` or the `focus`. From what I can tell, the content of the class has no effect.

I am using version 4.2.0

**Comment by GenaBitu** [comment]
I tried profiling the problem and 99% of the time is spent in
`RegExp: ^((\[[^\]]*\]|\([^\)]*\))?[^\[\]\(\)]*)*\.`

**Comment by GenaBitu** [comment]
[processed.txt](https://github.com/anandthakker/doiuse/files/3008350/processed.txt)

**Comment by GenaBitu** [comment]
See here - catastrophic backtracking:
https://regex101.com/r/MlbAhW/1
